import { UserRole } from '@prisma/client';

export const Permission = {
  BRANCH_VIEW: 'BRANCH_VIEW',
  BRANCH_MANAGE: 'BRANCH_MANAGE',

  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_MANAGE: 'PRODUCT_MANAGE',

  SUPPLIER_VIEW: 'SUPPLIER_VIEW',
  SUPPLIER_MANAGE: 'SUPPLIER_MANAGE',

  USER_VIEW: 'USER_VIEW',
  USER_MANAGE: 'USER_MANAGE',

  STOCK_REQUIREMENT_CREATE: 'STOCK_REQUIREMENT_CREATE',
  STOCK_REQUIREMENT_VIEW: 'STOCK_REQUIREMENT_VIEW',
  STOCK_REQUIREMENT_APPROVE: 'STOCK_REQUIREMENT_APPROVE',

  PURCHASE_ORDER_CREATE: 'PURCHASE_ORDER_CREATE',
  PURCHASE_ORDER_VIEW: 'PURCHASE_ORDER_VIEW',
  PURCHASE_ORDER_APPROVE: 'PURCHASE_ORDER_APPROVE',

  GOODS_RECEIPT_CREATE: 'GOODS_RECEIPT_CREATE',
  GOODS_RECEIPT_VIEW: 'GOODS_RECEIPT_VIEW',
  GOODS_RECEIPT_POST: 'GOODS_RECEIPT_POST',

  RECEIPT_CORRECTION_CREATE: 'RECEIPT_CORRECTION_CREATE',
  RECEIPT_CORRECTION_VIEW: 'RECEIPT_CORRECTION_VIEW',

  SUPPLIER_INVOICE_CREATE: 'SUPPLIER_INVOICE_CREATE',
  SUPPLIER_INVOICE_VIEW: 'SUPPLIER_INVOICE_VIEW',

  CREDIT_NOTE_CREATE: 'CREDIT_NOTE_CREATE',
  CREDIT_NOTE_VIEW: 'CREDIT_NOTE_VIEW',

  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_ALLOCATE: 'PAYMENT_ALLOCATE',

  STOCK_TRANSFER_CREATE: 'STOCK_TRANSFER_CREATE',
  STOCK_TRANSFER_VIEW: 'STOCK_TRANSFER_VIEW',
  STOCK_TRANSFER_DISPATCH: 'STOCK_TRANSFER_DISPATCH',
  STOCK_TRANSFER_RECEIVE: 'STOCK_TRANSFER_RECEIVE',

  DISPENSING_CREATE: 'DISPENSING_CREATE',
  DISPENSING_VIEW: 'DISPENSING_VIEW',

  INVENTORY_VIEW: 'INVENTORY_VIEW',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  AUDIT_VIEW: 'AUDIT_VIEW',
} as const;

export type PermissionValue = (typeof Permission)[keyof typeof Permission];

const ALL_PERMISSIONS = Object.values(Permission) as PermissionValue[];

const READ_ONLY_BASE: PermissionValue[] = [
  Permission.BRANCH_VIEW,
  Permission.PRODUCT_VIEW,
  Permission.SUPPLIER_VIEW,
  Permission.INVENTORY_VIEW,
  Permission.DOCUMENT_VIEW,
];

export const ROLE_PERMISSIONS: Record<UserRole, PermissionValue[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  COMPANY_ADMIN: ALL_PERMISSIONS,
  CENTRAL_PHARMACY: [
    ...READ_ONLY_BASE,
    Permission.STOCK_REQUIREMENT_VIEW,
    Permission.STOCK_REQUIREMENT_APPROVE,
    Permission.PURCHASE_ORDER_CREATE,
    Permission.PURCHASE_ORDER_VIEW,
    Permission.PURCHASE_ORDER_APPROVE,
    Permission.GOODS_RECEIPT_CREATE,
    Permission.GOODS_RECEIPT_VIEW,
    Permission.GOODS_RECEIPT_POST,
    Permission.RECEIPT_CORRECTION_CREATE,
    Permission.RECEIPT_CORRECTION_VIEW,
    Permission.SUPPLIER_INVOICE_CREATE,
    Permission.SUPPLIER_INVOICE_VIEW,
    Permission.CREDIT_NOTE_CREATE,
    Permission.CREDIT_NOTE_VIEW,
    Permission.PAYMENT_CREATE,
    Permission.PAYMENT_VIEW,
    Permission.PAYMENT_ALLOCATE,
    Permission.STOCK_TRANSFER_CREATE,
    Permission.STOCK_TRANSFER_VIEW,
    Permission.STOCK_TRANSFER_DISPATCH,
    Permission.STOCK_TRANSFER_RECEIVE,
    Permission.AUDIT_VIEW,
  ],
  BRANCH_MANAGER: [
    ...READ_ONLY_BASE,
    Permission.STOCK_REQUIREMENT_CREATE,
    Permission.STOCK_REQUIREMENT_VIEW,
    Permission.STOCK_REQUIREMENT_APPROVE,
    Permission.STOCK_TRANSFER_VIEW,
    Permission.STOCK_TRANSFER_RECEIVE,
    Permission.DISPENSING_CREATE,
    Permission.DISPENSING_VIEW,
    Permission.AUDIT_VIEW,
  ],
  PHARMACIST: [
    ...READ_ONLY_BASE,
    Permission.STOCK_REQUIREMENT_CREATE,
    Permission.STOCK_REQUIREMENT_VIEW,
    Permission.STOCK_TRANSFER_VIEW,
    Permission.STOCK_TRANSFER_RECEIVE,
    Permission.DISPENSING_CREATE,
    Permission.DISPENSING_VIEW,
  ],
  STAFF: [
    ...READ_ONLY_BASE,
    Permission.STOCK_REQUIREMENT_CREATE,
    Permission.STOCK_REQUIREMENT_VIEW,
  ],
};

export function permissionsForRole(role: UserRole): PermissionValue[] {
  return ROLE_PERMISSIONS[role] ?? [];
}
